# Question 1

In [2]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm

In [3]:
data1=pd.read_csv('Cutlets.csv')
data1.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [4]:
unitA=pd.Series(data1.iloc[:,0])
unitA

0     6.8090
1     6.4376
2     6.9157
3     7.3012
4     7.4488
5     7.3871
6     6.8755
7     7.0621
8     6.6840
9     6.8236
10    7.3930
11    7.5169
12    6.9246
13    6.9256
14    6.5797
15    6.8394
16    6.5970
17    7.2705
18    7.2828
19    7.3495
20    6.9438
21    7.1560
22    6.5341
23    7.2854
24    6.9952
25    6.8568
26    7.2163
27    6.6801
28    6.9431
29    7.0852
30    6.7794
31    7.2783
32    7.1561
33    7.3943
34    6.9405
Name: Unit A, dtype: float64

In [5]:
unitB=pd.Series(data1.iloc[:,1])
unitB

0     6.7703
1     7.5093
2     6.7300
3     6.7878
4     7.1522
5     6.8110
6     7.2212
7     6.6606
8     7.2402
9     7.0503
10    6.8810
11    7.4059
12    6.7652
13    6.0380
14    7.1581
15    7.0240
16    6.6672
17    7.4314
18    7.3070
19    6.7478
20    6.8889
21    7.4220
22    6.5217
23    7.1688
24    6.7594
25    6.9399
26    7.0133
27    6.9182
28    6.3346
29    7.5459
30    7.0992
31    7.1180
32    6.6965
33    6.5780
34    7.3875
Name: Unit B, dtype: float64

In [6]:
# 2-sample 2-tail ttest:   stats.ttest_ind(array1,array2) (Independent samples)
p_value=stats.ttest_ind(unitA,unitB)
p_value

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

In [7]:
#for two tailes test.(Probability)
p_value[1]     


0.4722394724599501

# Question 2

In [8]:
import pandas as pd 
import numpy as np
from scipy import stats


In [9]:
data1=pd.read_csv("LabTAT.csv")
data1

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0          185.35        165.53        176.70        166.13
1          170.49        185.91        198.45        160.79
2          192.77        194.92        201.23        185.18
3          177.33        183.00        199.61        176.42
4          193.41        169.57        204.63        152.60
..            ...           ...           ...           ...
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

[120 rows x 4 columns]

In [10]:
stats.f_oneway(data1.iloc[0:,0],data1.iloc[0:,1],data1.iloc[0:,3])

F_onewayResult(statistic=42.9642878605358, pvalue=1.9085834249466044e-17)

# Question 3

In [11]:
data1=pd.read_csv("BuyerRatio.csv")
data1

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [12]:
data1_contengtable=data1.iloc[:,1:5]
data1_contengtable

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [13]:
data1_contengtable.values




array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]], dtype=int64)

In [14]:
z=stats.chi2_contingency(data1_contengtable)
z


(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [15]:
no_of_rows=len(data1_contengtable.iloc[0:2,0])
no_of_columns=len(data1_contengtable.iloc[0,0:4])
degree_of_f=(no_of_rows-1)*(no_of_columns-1)
print('Degree of Freedom=',degree_of_f)



Degree of Freedom= 3


In [16]:
Expected_values=z[3]
Expected_values

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

In [17]:
from scipy.stats import chi2
      

In [18]:
chi_2=sum([(o-e)**2/e for o,e in zip(data1_contengtable.values,Expected_values)])
chi_2_statistics=chi_2[0]+chi_2[1]
chi_2_statistics     

1.5152956451130446

In [19]:
critical_value=chi2.ppf(0.95,3)
critical_value

7.814727903251179

In [20]:
p_value=1-chi2.cdf(chi_2_statistics,3)
p_value

0.6787446296467897

# Question 4

In [21]:
COF=pd.read_csv('Costomer+OrderForm (1).csv')
COF

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [22]:
COF.describe()

Phillippines   Indonesia       Malta       India
count           300         300         300         300
unique            2           2           2           2
top      Error Free  Error Free  Error Free  Error Free
freq            271         267         269         280

In [23]:
COF.isnull().sum()

Phillippines    0
Indonesia       0
Malta           0
India           0
dtype: int64

In [24]:
contingency_tabel=[[271,267,269,280],[29,33,31,20]]
print(contingency_tabel)

[[271, 267, 269, 280], [29, 33, 31, 20]]


In [25]:
exp=stats.chi2_contingency(contingency_tabel)
exp

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [26]:
observed=np.array([271,267,269,280,29,33,31,20])
expected=np.array([271.75,271.75,271.75,271.75,28.25,28.25,28.25,28.25])

In [27]:
test_statistic,p_value=stats.chisquare(observed,expected,ddof=3)
test_statistic,p_value
print("Test Statistic=" , test_statistic , '\n' ,'p_value=',p_value)

Test Statistic= 3.858960685820355 
 p_value= 0.4254298144535761


In [28]:
#p=0.42542 we fail to reject Null Hypothesis